### ISSUE TITLE
update checker isn't async

### ISSUE THREAD

**Issue by kukelekuuk00** [lol7344/hubthat#1]
https://www.spigotmc.org/threads/need-a-support-sincerely-important-to-my-server.163133/

The update checker should be in a separate thread

**Comment by lol7344** [comment]
sorry for replying three years later, but this issue is fixed and the code is no longer open source. you can find the most updated and bug-free version on SpigotMC or BukkitDev.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
